### ISSUE TITLE
Несекретный секретный ключ

### ISSUE THREAD

**Issue by vaimon** [TeamBuilders/TeamCraft#4]
Кажется, ваш супер секретный ключ всё-таки не такой секретный. Я понимаю, что это может быть временно, но не забудьте потом убрать куда-то

https://github.com/TeamBuilders/TeamCraft/blob/78ff676528079b050e9b91b8a8bfca0875a420cb/Backend/TeamCraft/TeamCraft/JwtData/AuthOptions.cs#L10C6-L10C6

**Comment by HemulenEXE** [comment]
Спасибо за помощь, ключ из кода убрали
